version: '3.8'

services:
  app:
    build: .
    depends_on: 
      - db
    networks:
      - test

  db:
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_DB=db_labs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=23102002Papa
    ports:
      - 5432:5432
    networks:
      - test


networks:
  test:
  