version: '3.8'
services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 23102002Papa
            POSTGRES_DB: db_labs
        ports:
            - 5432:5432
        networks:
            - default

    redis:
        image: redis
        networks:
            - default

    nad:
        build: ./Loshara_na_massa_nabori_bez_havku_den_2_vnochi/
        depends_on:
            - db
        volumes:
            - ./app:/usr/src/app
        networks:
            - default
        environment:
            PYTHONUNBUFFERED: 1

    app:
        build: ./app/
        depends_on:
            - db
            - redis
        volumes:
            - ./app:/usr/src/app
        networks:
            - default

        environment:
            PYTHONUNBUFFERED: 1
        ports: 
            - 5000:5000

    flyway:
        image: flyway/flyway
        command: -url=jdbc:postgresql://db:5432/db_labs -user=postgres -password=23102002Papa -baselineOnMigrate=true migrate
        volumes:
            - "./flyway/sql:/flyway/sql"
        depends_on:
            - db
        networks:
            - default
    mongodb:
        image: mongo
        ports:
            - 27017:27017

networks:
    default:
        name: lnet
